use_frameworks!

platform :ios, '8.0'

target 'UUWebViewJavascriptBridge_Example' do
  pod 'UUWebViewJavascriptBridge', :path => '../'

  target 'UUWebViewJavascriptBridge_Tests' do
    inherit! :search_paths

    
  end
end
